// <auto-generated />
using System;
using HiddenWing.BrandCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiddenWing.BrandCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BrandDbContext))]
    [Migration("20260919081319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CompanyName = "Hidden Wing",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technology, products, solutions and digital ventures built under Hidden Wing.",
                            IsActive = true,
                            Name = "Hidden Wing",
                            Slug = "hidden-wing",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.BrandAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProductId");

                    b.ToTable("brand_assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000041"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileSize = 0L,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            Name = "Hidden Wing Logo",
                            Type = "Logo",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/assets/hidden-wing/logo.svg"
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000042"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileSize = 0L,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            Name = "Hidden Wing Logo Dark",
                            Type = "LogoDark",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/assets/hidden-wing/logo-dark.svg"
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000043"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileSize = 0L,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            Name = "Hidden Wing Logo Light",
                            Type = "LogoLight",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/assets/hidden-wing/logo-light.svg"
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000044"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileSize = 0L,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            Name = "Hidden Wing Icon",
                            Type = "Icon",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/assets/hidden-wing/icon.svg"
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000045"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileSize = 0L,
                            IsActive = true,
                            MimeType = "image/svg+xml",
                            Name = "Hidden Wing Favicon",
                            Type = "Favicon",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/assets/hidden-wing/favicon.svg"
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000046"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileSize = 0L,
                            IsActive = true,
                            MimeType = "image/png",
                            Name = "Hidden Wing OG Image",
                            Type = "OgImage",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "/assets/hidden-wing/og-image.png"
                        });
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000021"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Internal operations and company headquarters workspace.",
                            IsActive = true,
                            Name = "Hidden Wing HQ",
                            Slug = "hq",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000022"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commerce and catalog experience for Hidden Wing products.",
                            IsActive = true,
                            Name = "Hidden Wing Store",
                            Slug = "store",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000023"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Project delivery and collaboration workspace.",
                            IsActive = true,
                            Name = "Hidden Wing Projects",
                            Slug = "projects",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000024"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Data platform and reporting workspace.",
                            IsActive = true,
                            Name = "Hidden Wing Data",
                            Slug = "data",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000025"),
                            BrandId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative console for Hidden Wing operators.",
                            IsActive = true,
                            Name = "Hidden Wing Admin",
                            Slug = "admin",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.ProductBranding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BorderColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FontFamily")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoDarkUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LogoLightUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MutedTextColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PrivacyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SurfaceColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Tagline")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TextColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ThemeId");

                    b.ToTable("product_brandings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000031"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Hidden Wing HQ",
                            IsEnabled = true,
                            ProductId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000021"),
                            ShortName = "HQ",
                            Tagline = "Company operations, in one place.",
                            ThemeId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000010"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000032"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Hidden Wing Store",
                            IsEnabled = true,
                            ProductId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000022"),
                            ShortName = "Store",
                            Tagline = "Products and commerce under Hidden Wing.",
                            ThemeId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000010"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000033"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Hidden Wing Projects",
                            IsEnabled = true,
                            ProductId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000023"),
                            ShortName = "Projects",
                            Tagline = "Plan and deliver Hidden Wing work.",
                            ThemeId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000010"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000034"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Hidden Wing Data",
                            IsEnabled = true,
                            ProductId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000024"),
                            ShortName = "Data",
                            Tagline = "Insight from Hidden Wing systems.",
                            ThemeId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000010"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000035"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Hidden Wing Admin",
                            IsEnabled = true,
                            ProductId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000025"),
                            ShortName = "Admin",
                            Tagline = "Operate Hidden Wing platforms.",
                            ThemeId = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000010"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BorderRadius")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("MutedTextColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SurfaceColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a0f1c2e-3b4d-4e5f-9a01-000000000010"),
                            AccentColor = "#C6A15B",
                            BackgroundColor = "#F4EFE6",
                            BorderColor = "#D9D2C5",
                            BorderRadius = "8px",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FontFamily = "Inter, system-ui, sans-serif",
                            IsDefault = true,
                            MutedTextColor = "#5C6B7A",
                            Name = "Hidden Wing Default",
                            PrimaryColor = "#1C3353",
                            SecondaryColor = "#3E536B",
                            Slug = "hidden-wing-default",
                            SurfaceColor = "#FFFFFF",
                            TextColor = "#1A1F29",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.BrandAsset", b =>
                {
                    b.HasOne("HiddenWing.BrandCenter.Domain.Entities.Brand", "Brand")
                        .WithMany("Assets")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenWing.BrandCenter.Domain.Entities.Product", "Product")
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Product", b =>
                {
                    b.HasOne("HiddenWing.BrandCenter.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.ProductBranding", b =>
                {
                    b.HasOne("HiddenWing.BrandCenter.Domain.Entities.Product", "Product")
                        .WithOne("Branding")
                        .HasForeignKey("HiddenWing.BrandCenter.Domain.Entities.ProductBranding", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiddenWing.BrandCenter.Domain.Entities.Theme", "Theme")
                        .WithMany("ProductBrandings")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Product", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Branding");
                });

            modelBuilder.Entity("HiddenWing.BrandCenter.Domain.Entities.Theme", b =>
                {
                    b.Navigation("ProductBrandings");
                });
#pragma warning restore 612, 618
        }
    }
}
